var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_TUNDRA_1 = new ol.format.GeoJSON();
var features_TUNDRA_1 = format_TUNDRA_1.readFeatures(json_TUNDRA_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_TUNDRA_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_TUNDRA_1.addFeatures(features_TUNDRA_1);
var lyr_TUNDRA_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_TUNDRA_1, 
                style: style_TUNDRA_1,
                popuplayertitle: 'TUNDRA',
                interactive: false,
    title: 'TUNDRA<br />\
    <img src="styles/legend/TUNDRA_1_0.png" /> Bottom Quintile<br />\
    <img src="styles/legend/TUNDRA_1_1.png" /> 2nd Quintile<br />\
    <img src="styles/legend/TUNDRA_1_2.png" /> 3rd Quintile<br />\
    <img src="styles/legend/TUNDRA_1_3.png" /> 4th Quintile<br />\
    <img src="styles/legend/TUNDRA_1_4.png" /> 5th Quintile<br />' });
var format_LivingEnvironmentScore_2 = new ol.format.GeoJSON();
var features_LivingEnvironmentScore_2 = format_LivingEnvironmentScore_2.readFeatures(json_LivingEnvironmentScore_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_LivingEnvironmentScore_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_LivingEnvironmentScore_2.addFeatures(features_LivingEnvironmentScore_2);
var lyr_LivingEnvironmentScore_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_LivingEnvironmentScore_2, 
                style: style_LivingEnvironmentScore_2,
                popuplayertitle: 'Living Environment Score',
                interactive: false,
    title: 'Living Environment Score<br />\
    <img src="styles/legend/LivingEnvironmentScore_2_0.png" /> 3 - 15<br />\
    <img src="styles/legend/LivingEnvironmentScore_2_1.png" /> 15 - 28<br />\
    <img src="styles/legend/LivingEnvironmentScore_2_2.png" /> 28 - 40<br />\
    <img src="styles/legend/LivingEnvironmentScore_2_3.png" /> 40 - 52<br />\
    <img src="styles/legend/LivingEnvironmentScore_2_4.png" /> 52 - 65<br />' });
var format_HealthDeprivationandDisabilityScore_3 = new ol.format.GeoJSON();
var features_HealthDeprivationandDisabilityScore_3 = format_HealthDeprivationandDisabilityScore_3.readFeatures(json_HealthDeprivationandDisabilityScore_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_HealthDeprivationandDisabilityScore_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_HealthDeprivationandDisabilityScore_3.addFeatures(features_HealthDeprivationandDisabilityScore_3);
var lyr_HealthDeprivationandDisabilityScore_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_HealthDeprivationandDisabilityScore_3, 
                style: style_HealthDeprivationandDisabilityScore_3,
                popuplayertitle: 'Health Deprivation and Disability Score',
                interactive: false,
    title: 'Health Deprivation and Disability Score<br />\
    <img src="styles/legend/HealthDeprivationandDisabilityScore_3_0.png" /> -2.13 - -1.63<br />\
    <img src="styles/legend/HealthDeprivationandDisabilityScore_3_1.png" /> -1.63 - -1.12<br />\
    <img src="styles/legend/HealthDeprivationandDisabilityScore_3_2.png" /> -1.12 - -0.62<br />\
    <img src="styles/legend/HealthDeprivationandDisabilityScore_3_3.png" /> -0.62 - -0.11<br />\
    <img src="styles/legend/HealthDeprivationandDisabilityScore_3_4.png" /> -0.11 - 0.39<br />' });
var format_AccesstoHousingandServicesScore_4 = new ol.format.GeoJSON();
var features_AccesstoHousingandServicesScore_4 = format_AccesstoHousingandServicesScore_4.readFeatures(json_AccesstoHousingandServicesScore_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_AccesstoHousingandServicesScore_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_AccesstoHousingandServicesScore_4.addFeatures(features_AccesstoHousingandServicesScore_4);
var lyr_AccesstoHousingandServicesScore_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_AccesstoHousingandServicesScore_4, 
                style: style_AccesstoHousingandServicesScore_4,
                popuplayertitle: 'Access to Housing and Services Score ',
                interactive: false,
    title: 'Access to Housing and Services Score <br />\
    <img src="styles/legend/AccesstoHousingandServicesScore_4_0.png" /> 4.3 - 13.7<br />\
    <img src="styles/legend/AccesstoHousingandServicesScore_4_1.png" /> 13.7 - 23<br />\
    <img src="styles/legend/AccesstoHousingandServicesScore_4_2.png" /> 23 - 32.3<br />\
    <img src="styles/legend/AccesstoHousingandServicesScore_4_3.png" /> 32.3 - 41.7<br />\
    <img src="styles/legend/AccesstoHousingandServicesScore_4_4.png" /> 41.7 - 51<br />' });
var format_CrimeScore_5 = new ol.format.GeoJSON();
var features_CrimeScore_5 = format_CrimeScore_5.readFeatures(json_CrimeScore_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CrimeScore_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CrimeScore_5.addFeatures(features_CrimeScore_5);
var lyr_CrimeScore_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CrimeScore_5, 
                style: style_CrimeScore_5,
                popuplayertitle: 'Crime Score',
                interactive: false,
    title: 'Crime Score<br />\
    <img src="styles/legend/CrimeScore_5_0.png" /> -1.88 - -1.3<br />\
    <img src="styles/legend/CrimeScore_5_1.png" /> -1.3 - -0.72<br />\
    <img src="styles/legend/CrimeScore_5_2.png" /> -0.72 - -0.14<br />\
    <img src="styles/legend/CrimeScore_5_3.png" /> -0.14 - 0.43<br />\
    <img src="styles/legend/CrimeScore_5_4.png" /> 0.43 - 1.01<br />' });
var format_EducationSkillsandTrainingScore_6 = new ol.format.GeoJSON();
var features_EducationSkillsandTrainingScore_6 = format_EducationSkillsandTrainingScore_6.readFeatures(json_EducationSkillsandTrainingScore_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_EducationSkillsandTrainingScore_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_EducationSkillsandTrainingScore_6.addFeatures(features_EducationSkillsandTrainingScore_6);
var lyr_EducationSkillsandTrainingScore_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_EducationSkillsandTrainingScore_6, 
                style: style_EducationSkillsandTrainingScore_6,
                popuplayertitle: 'Education,  Skills,  and Training Score',
                interactive: false,
    title: 'Education,  Skills,  and Training Score<br />\
    <img src="styles/legend/EducationSkillsandTrainingScore_6_0.png" /> 0 - 12<br />\
    <img src="styles/legend/EducationSkillsandTrainingScore_6_1.png" /> 12 - 25<br />\
    <img src="styles/legend/EducationSkillsandTrainingScore_6_2.png" /> 25 - 37<br />\
    <img src="styles/legend/EducationSkillsandTrainingScore_6_3.png" /> 37 - 49<br />\
    <img src="styles/legend/EducationSkillsandTrainingScore_6_4.png" /> 49 - 62<br />' });
var format_EmploymentScore_7 = new ol.format.GeoJSON();
var features_EmploymentScore_7 = format_EmploymentScore_7.readFeatures(json_EmploymentScore_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_EmploymentScore_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_EmploymentScore_7.addFeatures(features_EmploymentScore_7);
var lyr_EmploymentScore_7 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_EmploymentScore_7, 
                style: style_EmploymentScore_7,
                popuplayertitle: 'Employment Score',
                interactive: false,
    title: 'Employment Score<br />\
    <img src="styles/legend/EmploymentScore_7_0.png" /> 0.011 - 0.037<br />\
    <img src="styles/legend/EmploymentScore_7_1.png" /> 0.037 - 0.063<br />\
    <img src="styles/legend/EmploymentScore_7_2.png" /> 0.063 - 0.089<br />\
    <img src="styles/legend/EmploymentScore_7_3.png" /> 0.089 - 0.115<br />\
    <img src="styles/legend/EmploymentScore_7_4.png" /> 0.115 - 0.141<br />' });
var format_IncomeScores_8 = new ol.format.GeoJSON();
var features_IncomeScores_8 = format_IncomeScores_8.readFeatures(json_IncomeScores_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_IncomeScores_8 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_IncomeScores_8.addFeatures(features_IncomeScores_8);
var lyr_IncomeScores_8 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_IncomeScores_8, 
                style: style_IncomeScores_8,
                popuplayertitle: 'Income Scores',
                interactive: false,
    title: 'Income Scores<br />\
    <img src="styles/legend/IncomeScores_8_0.png" /> 0.013 - 0.0446<br />\
    <img src="styles/legend/IncomeScores_8_1.png" /> 0.0446 - 0.0762<br />\
    <img src="styles/legend/IncomeScores_8_2.png" /> 0.0762 - 0.1078<br />\
    <img src="styles/legend/IncomeScores_8_3.png" /> 0.1078 - 0.1394<br />\
    <img src="styles/legend/IncomeScores_8_4.png" /> 0.1394 - 0.171<br />' });
var format_MultiScoreDeprivation_9 = new ol.format.GeoJSON();
var features_MultiScoreDeprivation_9 = format_MultiScoreDeprivation_9.readFeatures(json_MultiScoreDeprivation_9, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_MultiScoreDeprivation_9 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_MultiScoreDeprivation_9.addFeatures(features_MultiScoreDeprivation_9);
var lyr_MultiScoreDeprivation_9 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_MultiScoreDeprivation_9, 
                style: style_MultiScoreDeprivation_9,
                popuplayertitle: 'Multi-Score Deprivation',
                interactive: true,
    title: 'Multi-Score Deprivation<br />\
    <img src="styles/legend/MultiScoreDeprivation_9_0.png" /> 1 - 7<br />\
    <img src="styles/legend/MultiScoreDeprivation_9_1.png" /> 7 - 12<br />\
    <img src="styles/legend/MultiScoreDeprivation_9_2.png" /> 12 - 18<br />\
    <img src="styles/legend/MultiScoreDeprivation_9_3.png" /> 18 - 23<br />\
    <img src="styles/legend/MultiScoreDeprivation_9_4.png" /> 23 - 29<br />' });

lyr_OpenStreetMap_0.setVisible(true);lyr_TUNDRA_1.setVisible(true);lyr_LivingEnvironmentScore_2.setVisible(true);lyr_HealthDeprivationandDisabilityScore_3.setVisible(true);lyr_AccesstoHousingandServicesScore_4.setVisible(true);lyr_CrimeScore_5.setVisible(true);lyr_EducationSkillsandTrainingScore_6.setVisible(true);lyr_EmploymentScore_7.setVisible(true);lyr_IncomeScores_8.setVisible(true);lyr_MultiScoreDeprivation_9.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_TUNDRA_1,lyr_LivingEnvironmentScore_2,lyr_HealthDeprivationandDisabilityScore_3,lyr_AccesstoHousingandServicesScore_4,lyr_CrimeScore_5,lyr_EducationSkillsandTrainingScore_6,lyr_EmploymentScore_7,lyr_IncomeScores_8,lyr_MultiScoreDeprivation_9];
lyr_TUNDRA_1.set('fieldAliases', {'fid': 'fid', 'LSOA21CD': 'LSOA21CD', 'LSOA21NM': 'LSOA21NM', 'LSOA21NMW': 'LSOA21NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LAT': 'LAT', 'LONG': 'LONG', 'GlobalID': 'GlobalID', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'Deprivation — IoD2019 Scores_LSOA name (2011)', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'Deprivation — IoD2019 Scores_Local Authority District code (2019)', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'Deprivation — IoD2019 Scores_Local Authority District name (2019)', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'Deprivation — IoD2019 Scores_Income Score (rate)', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'Deprivation — IoD2019 Scores_Employment Score (rate)', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'Deprivation — IoD2019 Scores_Education, Skills and Training Score', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score', 'Deprivation — IoD2019 Scores_Crime Score': 'Deprivation — IoD2019 Scores_Crime Score', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score', 'Deprivation — IoD2019 Scores_Living Environment Score': 'Deprivation — IoD2019 Scores_Living Environment Score', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score', 'TUNDRA_total_pop': 'TUNDRA_total_pop', 'TUNDRA_progression_rate': 'TUNDRA_progression_rate', 'TUNDRA_quintile': 'TUNDRA_quintile', });
lyr_LivingEnvironmentScore_2.set('fieldAliases', {'fid': 'fid', 'LSOA21CD': 'LSOA21CD', 'LSOA21NM': 'LSOA21NM', 'LSOA21NMW': 'LSOA21NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LAT': 'LAT', 'LONG': 'LONG', 'GlobalID': 'GlobalID', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'Deprivation — IoD2019 Scores_LSOA name (2011)', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'Deprivation — IoD2019 Scores_Local Authority District code (2019)', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'Deprivation — IoD2019 Scores_Local Authority District name (2019)', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'Deprivation — IoD2019 Scores_Income Score (rate)', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'Deprivation — IoD2019 Scores_Employment Score (rate)', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'Deprivation — IoD2019 Scores_Education, Skills and Training Score', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score', 'Deprivation — IoD2019 Scores_Crime Score': 'Deprivation — IoD2019 Scores_Crime Score', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score', 'Deprivation — IoD2019 Scores_Living Environment Score': 'Deprivation — IoD2019 Scores_Living Environment Score', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score', });
lyr_HealthDeprivationandDisabilityScore_3.set('fieldAliases', {'fid': 'fid', 'LSOA21CD': 'LSOA21CD', 'LSOA21NM': 'LSOA21NM', 'LSOA21NMW': 'LSOA21NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LAT': 'LAT', 'LONG': 'LONG', 'GlobalID': 'GlobalID', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'Deprivation — IoD2019 Scores_LSOA name (2011)', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'Deprivation — IoD2019 Scores_Local Authority District code (2019)', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'Deprivation — IoD2019 Scores_Local Authority District name (2019)', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'Deprivation — IoD2019 Scores_Income Score (rate)', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'Deprivation — IoD2019 Scores_Employment Score (rate)', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'Deprivation — IoD2019 Scores_Education, Skills and Training Score', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score', 'Deprivation — IoD2019 Scores_Crime Score': 'Deprivation — IoD2019 Scores_Crime Score', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score', 'Deprivation — IoD2019 Scores_Living Environment Score': 'Deprivation — IoD2019 Scores_Living Environment Score', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score', });
lyr_AccesstoHousingandServicesScore_4.set('fieldAliases', {'fid': 'fid', 'LSOA21CD': 'LSOA21CD', 'LSOA21NM': 'LSOA21NM', 'LSOA21NMW': 'LSOA21NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LAT': 'LAT', 'LONG': 'LONG', 'GlobalID': 'GlobalID', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'Deprivation — IoD2019 Scores_LSOA name (2011)', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'Deprivation — IoD2019 Scores_Local Authority District code (2019)', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'Deprivation — IoD2019 Scores_Local Authority District name (2019)', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'Deprivation — IoD2019 Scores_Income Score (rate)', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'Deprivation — IoD2019 Scores_Employment Score (rate)', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'Deprivation — IoD2019 Scores_Education, Skills and Training Score', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score', 'Deprivation — IoD2019 Scores_Crime Score': 'Deprivation — IoD2019 Scores_Crime Score', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score', 'Deprivation — IoD2019 Scores_Living Environment Score': 'Deprivation — IoD2019 Scores_Living Environment Score', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score', });
lyr_CrimeScore_5.set('fieldAliases', {'fid': 'fid', 'LSOA21CD': 'LSOA21CD', 'LSOA21NM': 'LSOA21NM', 'LSOA21NMW': 'LSOA21NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LAT': 'LAT', 'LONG': 'LONG', 'GlobalID': 'GlobalID', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'Deprivation — IoD2019 Scores_LSOA name (2011)', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'Deprivation — IoD2019 Scores_Local Authority District code (2019)', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'Deprivation — IoD2019 Scores_Local Authority District name (2019)', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'Deprivation — IoD2019 Scores_Income Score (rate)', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'Deprivation — IoD2019 Scores_Employment Score (rate)', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'Deprivation — IoD2019 Scores_Education, Skills and Training Score', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score', 'Deprivation — IoD2019 Scores_Crime Score': 'Deprivation — IoD2019 Scores_Crime Score', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score', 'Deprivation — IoD2019 Scores_Living Environment Score': 'Deprivation — IoD2019 Scores_Living Environment Score', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score', });
lyr_EducationSkillsandTrainingScore_6.set('fieldAliases', {'fid': 'fid', 'LSOA21CD': 'LSOA21CD', 'LSOA21NM': 'LSOA21NM', 'LSOA21NMW': 'LSOA21NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LAT': 'LAT', 'LONG': 'LONG', 'GlobalID': 'GlobalID', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'Deprivation — IoD2019 Scores_LSOA name (2011)', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'Deprivation — IoD2019 Scores_Local Authority District code (2019)', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'Deprivation — IoD2019 Scores_Local Authority District name (2019)', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'Deprivation — IoD2019 Scores_Income Score (rate)', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'Deprivation — IoD2019 Scores_Employment Score (rate)', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'Deprivation — IoD2019 Scores_Education, Skills and Training Score', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score', 'Deprivation — IoD2019 Scores_Crime Score': 'Deprivation — IoD2019 Scores_Crime Score', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score', 'Deprivation — IoD2019 Scores_Living Environment Score': 'Deprivation — IoD2019 Scores_Living Environment Score', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score', });
lyr_EmploymentScore_7.set('fieldAliases', {'fid': 'fid', 'LSOA21CD': 'LSOA21CD', 'LSOA21NM': 'LSOA21NM', 'LSOA21NMW': 'LSOA21NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LAT': 'LAT', 'LONG': 'LONG', 'GlobalID': 'GlobalID', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'Deprivation — IoD2019 Scores_LSOA name (2011)', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'Deprivation — IoD2019 Scores_Local Authority District code (2019)', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'Deprivation — IoD2019 Scores_Local Authority District name (2019)', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'Deprivation — IoD2019 Scores_Income Score (rate)', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'Deprivation — IoD2019 Scores_Employment Score (rate)', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'Deprivation — IoD2019 Scores_Education, Skills and Training Score', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score', 'Deprivation — IoD2019 Scores_Crime Score': 'Deprivation — IoD2019 Scores_Crime Score', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score', 'Deprivation — IoD2019 Scores_Living Environment Score': 'Deprivation — IoD2019 Scores_Living Environment Score', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score', });
lyr_IncomeScores_8.set('fieldAliases', {'fid': 'fid', 'LSOA21CD': 'LSOA21CD', 'LSOA21NM': 'LSOA21NM', 'LSOA21NMW': 'LSOA21NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LAT': 'LAT', 'LONG': 'LONG', 'GlobalID': 'GlobalID', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'Deprivation — IoD2019 Scores_LSOA name (2011)', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'Deprivation — IoD2019 Scores_Local Authority District code (2019)', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'Deprivation — IoD2019 Scores_Local Authority District name (2019)', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'Deprivation — IoD2019 Scores_Income Score (rate)', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'Deprivation — IoD2019 Scores_Employment Score (rate)', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'Deprivation — IoD2019 Scores_Education, Skills and Training Score', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score', 'Deprivation — IoD2019 Scores_Crime Score': 'Deprivation — IoD2019 Scores_Crime Score', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score', 'Deprivation — IoD2019 Scores_Living Environment Score': 'Deprivation — IoD2019 Scores_Living Environment Score', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score', });
lyr_MultiScoreDeprivation_9.set('fieldAliases', {'fid': 'fid', 'LSOA21CD': 'LSOA21CD', 'LSOA21NM': 'LSOA21NM', 'LSOA21NMW': 'LSOA21NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LAT': 'LAT', 'LONG': 'LONG', 'GlobalID': 'GlobalID', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'Deprivation — IoD2019 Scores_LSOA name (2011)', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'Deprivation — IoD2019 Scores_Local Authority District code (2019)', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'Deprivation — IoD2019 Scores_Local Authority District name (2019)', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'Deprivation — IoD2019 Scores_Income Score (rate)', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'Deprivation — IoD2019 Scores_Employment Score (rate)', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'Deprivation — IoD2019 Scores_Education, Skills and Training Score', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score', 'Deprivation — IoD2019 Scores_Crime Score': 'Deprivation — IoD2019 Scores_Crime Score', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score', 'Deprivation — IoD2019 Scores_Living Environment Score': 'Deprivation — IoD2019 Scores_Living Environment Score', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score', });
lyr_TUNDRA_1.set('fieldImages', {'fid': 'TextEdit', 'LSOA21CD': 'TextEdit', 'LSOA21NM': 'TextEdit', 'LSOA21NMW': 'TextEdit', 'BNG_E': 'TextEdit', 'BNG_N': 'TextEdit', 'LAT': 'TextEdit', 'LONG': 'TextEdit', 'GlobalID': 'TextEdit', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Crime Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Living Environment Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'TextEdit', 'TUNDRA_total_pop': 'TextEdit', 'TUNDRA_progression_rate': 'TextEdit', 'TUNDRA_quintile': 'TextEdit', });
lyr_LivingEnvironmentScore_2.set('fieldImages', {'fid': 'TextEdit', 'LSOA21CD': 'TextEdit', 'LSOA21NM': 'TextEdit', 'LSOA21NMW': 'TextEdit', 'BNG_E': 'TextEdit', 'BNG_N': 'TextEdit', 'LAT': 'TextEdit', 'LONG': 'TextEdit', 'GlobalID': 'TextEdit', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Crime Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Living Environment Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'TextEdit', });
lyr_HealthDeprivationandDisabilityScore_3.set('fieldImages', {'fid': 'TextEdit', 'LSOA21CD': 'TextEdit', 'LSOA21NM': 'TextEdit', 'LSOA21NMW': 'TextEdit', 'BNG_E': 'TextEdit', 'BNG_N': 'TextEdit', 'LAT': 'TextEdit', 'LONG': 'TextEdit', 'GlobalID': 'TextEdit', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Crime Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Living Environment Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'TextEdit', });
lyr_AccesstoHousingandServicesScore_4.set('fieldImages', {'fid': 'TextEdit', 'LSOA21CD': 'TextEdit', 'LSOA21NM': 'TextEdit', 'LSOA21NMW': 'TextEdit', 'BNG_E': 'TextEdit', 'BNG_N': 'TextEdit', 'LAT': 'TextEdit', 'LONG': 'TextEdit', 'GlobalID': 'TextEdit', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Crime Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Living Environment Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'TextEdit', });
lyr_CrimeScore_5.set('fieldImages', {'fid': 'TextEdit', 'LSOA21CD': 'TextEdit', 'LSOA21NM': 'TextEdit', 'LSOA21NMW': 'TextEdit', 'BNG_E': 'TextEdit', 'BNG_N': 'TextEdit', 'LAT': 'TextEdit', 'LONG': 'TextEdit', 'GlobalID': 'TextEdit', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Crime Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Living Environment Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'TextEdit', });
lyr_EducationSkillsandTrainingScore_6.set('fieldImages', {'fid': 'TextEdit', 'LSOA21CD': 'TextEdit', 'LSOA21NM': 'TextEdit', 'LSOA21NMW': 'TextEdit', 'BNG_E': 'TextEdit', 'BNG_N': 'TextEdit', 'LAT': 'TextEdit', 'LONG': 'TextEdit', 'GlobalID': 'TextEdit', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Crime Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Living Environment Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'TextEdit', });
lyr_EmploymentScore_7.set('fieldImages', {'fid': 'TextEdit', 'LSOA21CD': 'TextEdit', 'LSOA21NM': 'TextEdit', 'LSOA21NMW': 'TextEdit', 'BNG_E': 'TextEdit', 'BNG_N': 'TextEdit', 'LAT': 'TextEdit', 'LONG': 'TextEdit', 'GlobalID': 'TextEdit', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Crime Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Living Environment Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'TextEdit', });
lyr_IncomeScores_8.set('fieldImages', {'fid': 'TextEdit', 'LSOA21CD': 'TextEdit', 'LSOA21NM': 'TextEdit', 'LSOA21NMW': 'TextEdit', 'BNG_E': 'TextEdit', 'BNG_N': 'TextEdit', 'LAT': 'TextEdit', 'LONG': 'TextEdit', 'GlobalID': 'TextEdit', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Crime Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Living Environment Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'TextEdit', });
lyr_MultiScoreDeprivation_9.set('fieldImages', {'fid': 'TextEdit', 'LSOA21CD': 'TextEdit', 'LSOA21NM': 'TextEdit', 'LSOA21NMW': 'TextEdit', 'BNG_E': 'TextEdit', 'BNG_N': 'TextEdit', 'LAT': 'TextEdit', 'LONG': 'TextEdit', 'GlobalID': 'TextEdit', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'TextEdit', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Crime Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Living Environment Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'TextEdit', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'TextEdit', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'TextEdit', });
lyr_TUNDRA_1.set('fieldLabels', {'fid': 'no label', 'LSOA21CD': 'no label', 'LSOA21NM': 'no label', 'LSOA21NMW': 'no label', 'BNG_E': 'no label', 'BNG_N': 'no label', 'LAT': 'no label', 'LONG': 'no label', 'GlobalID': 'no label', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'no label', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'no label', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'no label', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'no label', 'Deprivation — IoD2019 Scores_Crime Score': 'no label', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'no label', 'Deprivation — IoD2019 Scores_Living Environment Score': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'no label', 'TUNDRA_total_pop': 'no label', 'TUNDRA_progression_rate': 'no label', 'TUNDRA_quintile': 'no label', });
lyr_LivingEnvironmentScore_2.set('fieldLabels', {'fid': 'no label', 'LSOA21CD': 'no label', 'LSOA21NM': 'no label', 'LSOA21NMW': 'no label', 'BNG_E': 'no label', 'BNG_N': 'no label', 'LAT': 'no label', 'LONG': 'no label', 'GlobalID': 'no label', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'no label', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'no label', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'no label', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'no label', 'Deprivation — IoD2019 Scores_Crime Score': 'no label', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'no label', 'Deprivation — IoD2019 Scores_Living Environment Score': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'no label', });
lyr_HealthDeprivationandDisabilityScore_3.set('fieldLabels', {'fid': 'no label', 'LSOA21CD': 'no label', 'LSOA21NM': 'no label', 'LSOA21NMW': 'no label', 'BNG_E': 'no label', 'BNG_N': 'no label', 'LAT': 'no label', 'LONG': 'no label', 'GlobalID': 'no label', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'no label', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'no label', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'no label', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'no label', 'Deprivation — IoD2019 Scores_Crime Score': 'no label', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'no label', 'Deprivation — IoD2019 Scores_Living Environment Score': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'no label', });
lyr_AccesstoHousingandServicesScore_4.set('fieldLabels', {'fid': 'no label', 'LSOA21CD': 'no label', 'LSOA21NM': 'no label', 'LSOA21NMW': 'no label', 'BNG_E': 'no label', 'BNG_N': 'no label', 'LAT': 'no label', 'LONG': 'no label', 'GlobalID': 'no label', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'no label', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'no label', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'no label', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'no label', 'Deprivation — IoD2019 Scores_Crime Score': 'no label', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'no label', 'Deprivation — IoD2019 Scores_Living Environment Score': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'no label', });
lyr_CrimeScore_5.set('fieldLabels', {'fid': 'no label', 'LSOA21CD': 'no label', 'LSOA21NM': 'no label', 'LSOA21NMW': 'no label', 'BNG_E': 'no label', 'BNG_N': 'no label', 'LAT': 'no label', 'LONG': 'no label', 'GlobalID': 'no label', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'no label', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'no label', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'no label', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'no label', 'Deprivation — IoD2019 Scores_Crime Score': 'no label', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'no label', 'Deprivation — IoD2019 Scores_Living Environment Score': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'no label', });
lyr_EducationSkillsandTrainingScore_6.set('fieldLabels', {'fid': 'no label', 'LSOA21CD': 'no label', 'LSOA21NM': 'no label', 'LSOA21NMW': 'no label', 'BNG_E': 'no label', 'BNG_N': 'no label', 'LAT': 'no label', 'LONG': 'no label', 'GlobalID': 'no label', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'no label', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'no label', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'no label', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'no label', 'Deprivation — IoD2019 Scores_Crime Score': 'no label', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'no label', 'Deprivation — IoD2019 Scores_Living Environment Score': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'no label', });
lyr_EmploymentScore_7.set('fieldLabels', {'fid': 'no label', 'LSOA21CD': 'no label', 'LSOA21NM': 'no label', 'LSOA21NMW': 'no label', 'BNG_E': 'no label', 'BNG_N': 'no label', 'LAT': 'no label', 'LONG': 'no label', 'GlobalID': 'no label', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'no label', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'no label', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'no label', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'no label', 'Deprivation — IoD2019 Scores_Crime Score': 'no label', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'no label', 'Deprivation — IoD2019 Scores_Living Environment Score': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'no label', });
lyr_IncomeScores_8.set('fieldLabels', {'fid': 'no label', 'LSOA21CD': 'no label', 'LSOA21NM': 'no label', 'LSOA21NMW': 'no label', 'BNG_E': 'no label', 'BNG_N': 'no label', 'LAT': 'no label', 'LONG': 'no label', 'GlobalID': 'no label', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'no label', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'no label', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'no label', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'no label', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'no label', 'Deprivation — IoD2019 Scores_Crime Score': 'no label', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'no label', 'Deprivation — IoD2019 Scores_Living Environment Score': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'no label', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'no label', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'no label', });
lyr_MultiScoreDeprivation_9.set('fieldLabels', {'fid': 'hidden field', 'LSOA21CD': 'hidden field', 'LSOA21NM': 'header label - always visible', 'LSOA21NMW': 'inline label - visible with data', 'BNG_E': 'hidden field', 'BNG_N': 'hidden field', 'LAT': 'hidden field', 'LONG': 'hidden field', 'GlobalID': 'hidden field', 'Deprivation — IoD2019 Scores_LSOA name (2011)': 'hidden field', 'Deprivation — IoD2019 Scores_Local Authority District code (2019)': 'hidden field', 'Deprivation — IoD2019 Scores_Local Authority District name (2019)': 'hidden field', 'Deprivation — IoD2019 Scores_Index of Multiple Deprivation (IMD) Score': 'hidden field', 'Deprivation — IoD2019 Scores_Income Score (rate)': 'hidden field', 'Deprivation — IoD2019 Scores_Employment Score (rate)': 'hidden field', 'Deprivation — IoD2019 Scores_Education, Skills and Training Score': 'hidden field', 'Deprivation — IoD2019 Scores_Health Deprivation and Disability Score': 'hidden field', 'Deprivation — IoD2019 Scores_Crime Score': 'hidden field', 'Deprivation — IoD2019 Scores_Barriers to Housing and Services Score': 'hidden field', 'Deprivation — IoD2019 Scores_Living Environment Score': 'hidden field', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Children Index (IDACI) Score (rate)': 'hidden field', 'Deprivation — IoD2019 Scores_Income Deprivation Affecting Older People (IDAOPI) Score (rate)': 'hidden field', 'Deprivation — IoD2019 Scores_Children and Young People Sub-domain Score': 'hidden field', 'Deprivation — IoD2019 Scores_Adult Skills Sub-domain Score': 'hidden field', 'Deprivation — IoD2019 Scores_Geographical Barriers Sub-domain Score': 'hidden field', 'Deprivation — IoD2019 Scores_Wider Barriers Sub-domain Score': 'hidden field', 'Deprivation — IoD2019 Scores_Indoors Sub-domain Score': 'hidden field', 'Deprivation — IoD2019 Scores_Outdoors Sub-domain Score': 'hidden field', });
lyr_MultiScoreDeprivation_9.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});